Improved ghostty config and stay connected tmux script

diff --git a/bin/stay-connected-bs-tmux b/bin/stay-connected-bs-tmux
--- a/bin/stay-connected-bs-tmux
+++ b/bin/stay-connected-bs-tmux
@@ -5,8 +5,14 @@ IFS=$'\n\t'
 #tmux rename-window $3
 
 while true; do
-	{
-		ssh -o ConnectTimeout=10 -o ServerAliveInterval=2 -o ServerAliveCountMax=4 $1@$2 -t "source ~/bin/.find_zsh_path && zsh ~/projects/my-enviroment/bin/setup-ssh-agent.zsh && ~/bin/tmuxp load $3 -y"
-	}
-	wait-for-host $2
+  {
+    ssh -o ConnectTimeout=10 -o ServerAliveInterval=2 -o ServerAliveCountMax=4 $1@$2 -t "source ~/bin/.find_zsh_path && zsh ~/projects/my-enviroment/bin/setup-ssh-agent.zsh && ~/bin/tmuxp load $3 -y"
+    if [ $? -eq 0 ]; then
+      echo "Succesfull exit "
+      exit 0
+    else
+      echo "SSH FAILED"
+    fi
+  }
+  wait-for-host $2
 done
